[build]
  command = ""
  functions = "netlify/functions"
  publish = "netlify_public"

[dev]
  command = "python app.py"
  port = 5000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"
  included_files = ["app.py", "utils/**", "templates/**", "static/**", "resume_history.db"]
