[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "netlify_public"

[dev]
  command = "python app.py"
  port = 5000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200
  force = true


[functions]
  external_node_modules = []
  node_bundler = "esbuild"
